docs/requirements-docs.txt
docs/source/API/cell_tracking_metrics.track_errors.rst
docs/source/conf.py
docs/source/index.rst
pyproject.toml
src/cell_tracking_metrics/matchers/iou.py
src/cell_tracking_metrics/track_errors/__init__.py
src/cell_tracking_metrics/track_errors/division_events.py
src/cell_tracking_metrics/track_errors/divisions.py
src/cell_tracking_metrics/utils.py
tests/matchers/test_iou.py
tests/track_errors/test_divisions.py

Introduces division classification with temporal tolerance that requires that parents and daughters match.
Also cleans up a few things associated with documentation.

Add division evaluation with temporal tolerance

---

src/cell_tracking_metrics/matchers/compute_overlap.py
src/cell_tracking_metrics/matchers/iou.py

Extract function to get overlapping labels for use in both ctc matcher and iou matcher.

Pull code to get overlapping labels out into its own function

---

src/traccuracy/run_metrics.py

Fix results return and support matcher kwargs

---

src/traccuracy/__init__.py
src/traccuracy/_tracking_graph.py
tests/test_tracking_graph.py

Addresses most of #43, except updating all references.

Create Enums for our Node and Edge Attribute strings

---

src/traccuracy/_tracking_graph.py
tests/test_tracking_graph.py

Add function to extract tracklets

---

src/traccuracy/matchers/_iou.py
src/traccuracy/metrics/__init__.py
src/traccuracy/metrics/_divisions.py

Fixes outstanding issues with docstrings to close #72 

Fix subclass docstrings for sphinx autoapi

---

src/traccuracy/__init__.py
src/traccuracy/_run_metrics.py
src/traccuracy/track_errors/_ctc.py

this might be a better way to avoid circular imports, and appears to work for docs too

fix import loop

---

docs/source/metrics/ctc.rst

Add initial explanations for DET, TRA and AOGM measures.

Expand CTC DET Measure docs

---

examples/ctc.ipynb
src/traccuracy/_run_metrics.py
src/traccuracy/_tracking_graph.py
src/traccuracy/loaders/_ctc.py
src/traccuracy/matchers/_base.py
src/traccuracy/metrics/_base.py
src/traccuracy/metrics/_ctc.py
src/traccuracy/metrics/_divisions.py
src/traccuracy/metrics/_track_overlap.py
tests/bench.py
tests/matchers/test_base.py
tests/metrics/test_ctc_metrics.py
tests/metrics/test_divisions.py
tests/metrics/test_track_overlap_metrics.py
tests/test_run_metrics.py

Create a `Results` class for storing metric output with associated metadata

---

pyproject.toml

Add pyarrow dependency to resolve CI build issues

Add pyarrow to pyproject

---

src/traccuracy/_tracking_graph.py
src/traccuracy/matchers/_compute_overlap.py
tests/matchers/test_compute_overlap.py
tests/test_tracking_graph.py
tests/test_utils.py

Fix CTC matching for emtpy frames

---

src/traccuracy/matchers/_iou.py
tests/matchers/test_iou.py

- Don't allow threshold of 0.0 when one-to-one is False (because then everything will match to everything)
- Threshold the IOU matrix before doing linear sum assignment and only include things above threshold
- Increase the cost for non-viable matches (things with 0 in the IOU matrix including: matches below threshold, matches with no overlap, and matches to dummy nodes that don't actually exist) to be above the unmatched threshold
Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Fix multiple IOU-related bugs

---

.github/workflows/benchmark-report.yml

The data needs to be cache-retrieved/downloaded/cached also in the main benchmark report action.
Which topics does your change affect?
- CI &  benchmarks

Add data download to benchmark report action

---

.github/workflows/ci.yml
examples/ctc.ipynb

Fixes #195 for now and adds notebook execution into our CI workflow.
I still think we should implement the more relaxed matcher validation discussed in #194, but this PR at least gets the notebook running and will catch any other errors that pop up while we are making a lot of changes.
- Examples

Update example notebooks and run in CI

---

src/traccuracy/loaders/_ctc.py

Fixes #165 by essentially copying and pasting Draga's example and fixing one variable name 😆 Thanks @DragaDoncila !!
- Loaders

Pre-allocate numpy array and populate during reading for ctc loader

---

examples/ctc.ipynb
src/traccuracy/_run_metrics.py
src/traccuracy/cli.py
tests/test_run_metrics.py

Returning the `Matched` object allows someone who used the `run_metrics` function to interact with the annotated graphs afterwards. 

Update run metrics to return results and matched object

---

.github/workflows/ci.yml
pixi.lock
pyproject.toml
scripts/test_case_report.py
src/traccuracy/matchers/_compute_overlap.py
src/traccuracy/matchers/_iou.py
src/traccuracy/matchers/_point.py
tests/examples/graphs.py
tests/examples/segs.py
tests/matchers/test_compute_overlap.py
tests/matchers/test_iou.py
tests/metrics/test_divisions.py
tests/track_errors/test_divisions.py

Drop support for python 3.9. Closes #216 

Drop python 39

---

.pre-commit-config.yaml
pyproject.toml
src/traccuracy/_tracking_graph.py
src/traccuracy/cli.py
src/traccuracy/loaders/_ctc.py
src/traccuracy/matchers/_base.py
src/traccuracy/matchers/_compute_overlap.py
src/traccuracy/matchers/_ctc.py
src/traccuracy/matchers/_iou.py
src/traccuracy/matchers/_point.py
src/traccuracy/metrics/_base.py
src/traccuracy/metrics/_basic.py
src/traccuracy/metrics/_ctc.py
src/traccuracy/metrics/_divisions.py
src/traccuracy/metrics/_track_overlap.py
src/traccuracy/track_errors/_ctc.py
src/traccuracy/track_errors/basic.py
src/traccuracy/track_errors/divisions.py
tests/matchers/test_iou.py

Closes #94 
- Loaders
- Matchers
- Track Errors
- Metrics

Fully type traccuracy

---

developer_notes.md

Closes #213 
- Documentation update

Update dev docs with instructions to use pixi for building docs

---

src/traccuracy/loaders/_ctc.py
tests/loaders/test_ctc.py

CTC loader checks dimensionality of data to set TrackingGraph loc keys

---

src/traccuracy/matchers/_point.py

Sort nodes to ensure point matcher is deterministic

---

src/traccuracy/loaders/__init__.py
src/traccuracy/loaders/_point.py
tests/bench.py
tests/loaders/test_point.py

Closes #219 
Currently I'm assuming that the csv-like file contains node positions (t, z, y, x) and a "parent" column that specifies the node id of the parent node in the previous timepoint. If there is another common way of dumping to a csv where the edges are encoded differently, lmk and I can add support for it.
- Loaders
If this is a relatively large or complex …

Load csv into TrackingGraph

---

src/traccuracy/_tracking_graph.py
src/traccuracy/track_errors/_ctc.py
src/traccuracy/track_errors/basic.py
tests/test_tracking_graph.py

Remove get subgraph

---

pyproject.toml
src/traccuracy/_tracking_graph.py
tests/test_tracking_graph.py

Closes #91 and also adds checking for the label_key if segmentation is included in the TrackingGraph

Move TrackGraph node attr validation into a separate function with flag

---

.github/workflows/ci.yml
README.md
developer_notes.md
tests/matchers/test_iou.py
tests/track_errors/test_ctc_errors.py

Links in the readme and a couple other places were still pointing to the old org. Most of them redirected, but a few were broken so this PR sets them all to point to the new org.

Update links throughout repo to point to new litt org

---

docs/source/test_cases/index.md
docs/source/test_cases/larger_examples.md
tests/examples/larger_examples.py

Add a larger example to the test cases with multiple lineages. Illustrate it in the documentation.
- Track Errors
- Metrics

Add a larger test case with multiple tracks and frames

---

src/traccuracy/loaders/_ctc.py
tests/loaders/test_ctc.py

If you are implementing a new matcher or metric, please append this `&template=new_matcher_metric.md` to your url to load the correct template.
Briefly describe the contribution. If it resolves an issue or feature request, be sure to link to that issue.
- Documentation update
- Loaders
- Matchers
- Track Errors
- Metrics
Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're …

Tweak node ID assignment to avoid dataframe lookups

---

tests/examples/graphs.py
tests/examples/segs.py
tests/matchers/test_ctc.py
tests/matchers/test_iou.py
tests/matchers/test_point_seg.py
tests/test_tracking_graph.py
tests/test_utils.py

Towards #280, but excludes the track overlap tests 😬 

Update test cases to remove string ids 

---

src/traccuracy/loaders/_ctc.py
tests/loaders/test_ctc.py

Contributes towards #280
- Loaders

Refactor ctc loader to use uint ids

---

.gitignore
pyproject.toml
src/traccuracy/loaders/__init__.py
src/traccuracy/loaders/_geff.py
tests/loaders/test_geff.py

Implement a loader for geff data

---

src/traccuracy/loaders/__init__.py
src/traccuracy/loaders/_ctc.py
tests/bench.py
tests/loaders/test_ctc.py
tests/matchers/test_iou.py

Remove two private functions from public export and make `load_tiffs` public.
- Loaders

Remove some ctc functions from public export

---

src/traccuracy/_tracking_graph.py
src/traccuracy/loaders/_point.py
tests/loaders/test_point.py
tests/matchers/test_iou.py
tests/test_tracking_graph.py
tests/test_utils.py
tests/track_errors/test_ctc_errors.py

Check that node ids are positive integers

---

src/traccuracy/_run_metrics.py
tests/test_run_metrics.py

Expose relax skips as an option in run_metrics

---

pyproject.toml
src/traccuracy/_tracking_graph.py
src/traccuracy/metrics/_complete_tracks.py
src/traccuracy/utils.py
tests/test_tracking_graph.py

Closes #291 by removing the "is_" prefix from Node/EdgeFlags and switching to using `.value` wherever we use a flag. This should also simplify exporting to geff and unblock #309 
If this is a relatively large or complex change, kick off the discussion by explaining why you …

Use Flag.value for storing flags on graph
