live-image-tracking-tools/traccuracy

- src/cell_tracking_metrics/matchers/__init__.py
- src/cell_tracking_metrics/matchers/matched.py
- src/cell_tracking_metrics/metrics/__init__.py
- src/cell_tracking_metrics/metrics/base.py
- Add `Matched` class which takes `TrackingData` objects for gt and pred, and computes matching. Each current matching method will be a subclass of `Matched` e.g. `CTCMatched` or `IOUMatched`. The `Matched` objects will store both gt and pred data, as well as the mapping, and any additional private attributes that may be needed/used e.g. detection matrices.
- `Metrics` class is an abstract base class whose purpose is to take `Matched` objects and compute metrics based on the declared criteria. The `Matched` object passed in must fit the criteria declared by the subclasses of `Metrics` e.g. `CTCMetric` will declare that it `needs_det_matrix` and `Matched` objects without that attribute will raise an error.
- The `compute` methods of `Metric` objects return a dictionary with counts and …
> Add base classes for new api

- src/cell_tracking_metrics/tracking_graph.py
Rather than requiring matchers to take the `label_key` as a parameter, store it on the `TrackingGraph` during loading.
> Add label_key to TrackingGraph

- src/traccuracy/matchers/_ctc.py
CTC matcher previously assumed `label_key` would be the same for `gt` and `pred` graphs. Obviously this may not be the case, so updating this.
> Use appropriate label key for `gt` and `pred` graphs in `ctc` matching

- examples/ctc.ipynb
- src/traccuracy/matchers/_ctc.py
- src/traccuracy/metrics/_base.py
- src/traccuracy/metrics/_ctc.py
- src/traccuracy/track_errors/_ctc.py
- tests/matchers/test_ctc.py
- tests/track_errors/test_ctc_errors.py
The original AOGM paper uses "detection matrices" to allow for quick error counting. However, because we are assigning `tp`/`fp` etc. attributes to each node, we don't benefit from this quick counting - we still have to iterate through the graph.
This PR removes the reliance on detection matrices and computes the errors directly on the mapping. This should also mean we can use the AOGM/CTC metric with other matchers, assuming they are one-to-one or many-to-one (can't do one-to-many).
> Remove detection matrix computation

- src/traccuracy/loaders/_ctc.py
- src/traccuracy/matchers/_compute_overlap.py
- src/traccuracy/matchers/_ctc.py
- src/traccuracy/matchers/_iou.py
- src/traccuracy/track_errors/_ctc.py
Thanks a lot for this nice package, its really great to finally have proper tracking metrics in python! 
I noticed that `run_metrics` is relatively slow for medium sized datasets (e.g. ~30s for the hela demo dataset) so this PR just add some small code changes that should improve the metrics calculations by a factor of 6-10x. 
Specifically:
- iou/overlap caluclation on slices rather than the full segmentations masks 
- vectorization of edge indexing 
With that the following 
```python 
from traccuracy import run_metrics
from traccuracy.loaders import load_ctc_data
from traccuracy.matchers import CTCMatched, IOUMatched
from traccuracy.metrics import CTCMetrics, DivisionMetrics
from timeit import default_timer
gt_data = load_ctc_data(
'downloads/Fluo-N2DL-HeLa/01_GT/TRA', …
```
> Faster matchings/metrics

- src/traccuracy/cli.py
- src/traccuracy/matchers/_matched.py
Allows fine-grained control of messages printed to console when using traccuracy as a third-party library.
> Use logging API

- .github/workflows/benchmark-report.yml
- .github/workflows/ci.yml
- pyproject.toml
- tests/bench.py
This PR introduces a preliminary workflow for monitoring performance as part of our CI. It uses `pytest-benchmark` and `github-action-benchmark`.
Currently it runs on the Fluo-ND2L-HeLa dataset with the sample solution graph that we have stored in `examples/sample-data` and measures the following:
- loading gt data
- loading predicted data
- IOU matching
- CTC matching
- CTC metrics
- Division metrics (on both iou matched and ctc matched)
@DragaDoncila @bentaculum @cmalinmayor let me know what you all think at least about `tests/bench.py`. I am considering this to be a pretty minimal first set of measurements just so that we have some sort of baseline to work off of, but let me know if you see anything else that we should add in this first iteration.
The testing workflow can be run …
> Add basic set of performance benchmarking tests

- .github/workflows/benchmark-pr.py
- .github/workflows/ci.yml
- pyproject.toml
I couldn't get the `github-actions-benchmark` to perform the way I wanted for PRs (although it's working great for generating the charts on github pages). Instead I wrote a slightly more manual action that I think gives us what we want.
The benchmarking action triggered for each PR now does the following:
- Checks if benchmarks have been cached for the base commit and computes and saves them if not
- Runs benchmarking for the current commit 
- Generates a table comparing the mean runtime for head and base with the percent change
- Comments on the commit with the comparison table
@bentaculum are there any other statistics that you would want to see in that table?
> Improve the benchmarking workflow to generate a commit comment on PRs

- .github/workflows/benchmark-pr.py
- .github/workflows/ci.yml
See https://github.com/Janelia-Trackathon-2023/traccuracy/pull/64#issuecomment-1760249229 for a description of the issue with commenting on forked repos.
This PR changes the benchmark action to print a copy of the report to the logs so that the results are always visible. The commit comment is only generated if the source repo for the PR is not a fork.
> Improve benchmark action when running on repo forks

- tests/bench.py
With the merge of #54, the benchmarking assertion about the number of wrong semantic edges in our test candidate graph changed. I'm not entirely sure why but given that we were changing how wrong semantic is assigned I am not entirely surprised. This PR corrects the assertion so that benchmarking should pass.
> Correct benchmarking tests assertion for wrong semantic edges

- src/traccuracy/_tracking_graph.py
- tests/test_tracking_graph.py
Changes to `TrackingGraph` to improve performance related to attributes:
- Store dictionaries from NodeAttrs -> node ids and EdgeAttrs -> edge ids to efficiently access all nodes/edges with given attribute
- Use those dictionaries in `get_nodes_with_flag()`, `get_edges_with_flag()`, and `get_nodes_by_roi()`
- Speed up accessing node/edge attributes with specific functions `get_node_attribute()` and `get_edge_attribute()`, instead of having to go through `nodes()` and `edges()` dictionaries
- Speed up subgraph function by not re-computing all dictionaries from attrs to ids, but instead using intersection of sets of ids.
- Use `collections.Counter` in TrackingGraph test cases to make them order invariant
Closes #61
> Speed up accessing nodes/edges by attribute and node/edge attributes

- src/traccuracy/_tracking_graph.py
- src/traccuracy/track_errors/_ctc.py
When calculating edge errors, there is a 1-to-1 mapping between computed graph nodes and GT graph nodes, see details below.
It is faster to use a dictionary for doing the node mapping with O(n log(n)) runtime, compared to repeatedly iterating over a list with np.where (O(n^2)).
Details: Potential 1-to-many matches, namely computed nodes that match multiple GT nodes (called non-split), are not part of the induced graph. Therefore, all edges incident to such nodes are also not part of the induced graph, leaving us with the desired 1-to-1 mapping for all nodes that are incident to existing edges in the induced graph, which we iterate over in the loop for finding FP edges.
Conversely, each GT node is only matched to at most one computed node, directly yielding the 1-1 matching for finding FN …
> Speed up CTC edge errors

- .github/workflows/ci.yml
- README.md
- pyproject.toml
- src/traccuracy/__init__.py
> test: enable codecov

- .pre-commit-config.yaml
- pyproject.toml
- src/traccuracy/matchers/_compute_overlap.py
- src/traccuracy/matchers/_matched.py
- src/traccuracy/metrics/_base.py
- src/traccuracy/metrics/_divisions.py
- src/traccuracy/track_errors/divisions.py
- tests/bench.py
- tests/metrics/test_divisions.py
- tests/track_errors/test_divisions.py
This pr runs `pre-commit autoupdate`, to bring the linting deps up to date... and (all of these are optionally and can be removed if you like):
1. adds [the `TID` tidy-imports rule](https://docs.astral.sh/ruff/rules/#flake8-tidy-imports-tid), which enforces the absolute import patterns you've generally been following here.
2. adds [the `TCH` type-checking rule](https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch) which nicely catches cases where an import should be removed from, or moved to, an `if TYPE_CHECKING` block (it can autofix it too)
3. adds https://github.com/crate-ci/typos to the checks, which is a nice, fast, rust-based code-spelling checker (it caught and fixed few issues in the docstrings, also included here)
closes #33
> style: update pre-commit

- .readthedocs.yml
- README.md
- docs/source/cli.rst
- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
- src/traccuracy/_tracking_graph.py
- src/traccuracy/cli.py
- src/traccuracy/loaders/_ctc.py
- src/traccuracy/matchers/_iou.py
- src/traccuracy/metrics/_divisions.py
This fixes #67 and gets docs building again.   I did it by playing around with dependencies, and ultimately found that updating everything to the newest versions worked best (I removed m2r2 in favor of `myst-parser`, which helped with one of the docutils conflicts... I believe myst is now the recommended way to incorporate markdown in rst sources).
I would be curious to hear from @cmalinmayor whether the list rendering bug that necessitated the pins in 3b0be126ca104191483700bd4dfab000b5616f40 is "back" with this PR...  but I wasn't able to find anything weird looking?  bullets seem fine?
I did hard pin everything in the docs deps, which is optional and can be undone if you prefer, but I don't hesitate to pin all my docs requirements if I feel like it is a possibly fragile blend of …
> docs: fix docs build, fix all build warnings, enable strict mode

- src/traccuracy/loaders/__init__.py
- src/traccuracy/loaders/_ctc.py
- src/traccuracy/metrics/_divisions.py
- tests/bench.py
This adds some checks to enforce proper Cell Tracking Challenge data format already while loading, and prints descriptive error messages.
As discussed in the last meeting, they are turned on by default, but can be turned off with a boolean in `load_ctc_data`.
I've been dealing with tracking results in faulty CTC format recently and ran into weird errors downstream of the loader in the metrics computation, which inspired this PR.
The proposed routine checks:
- unique positive integer track IDs
- indicated parent IDs present
- parent tracklet ends before child tracklet starts (gaps possible)
- masks contain all detections as indicated in tracks file, and vice versa.
> Add CTC format checks in loader

- src/traccuracy/cli.py
- src/traccuracy/metrics/_divisions.py
- src/traccuracy/track_errors/divisions.py
- tests/metrics/test_divisions.py
- tests/track_errors/test_divisions.py
Closes #100 by making the behavior associated with the frame buffer parameter more explicit. The user specifies the maximum size of the frame buffer and we evaluate divisions over [0, max_frame_buffer].
> Change `frame_buffer` kwarg to `max_frame_buffer`

- src/traccuracy/matchers/_ctc.py
For obtaining single-frame segmentation-label to node id mappings, for larger graphs it is faster to only get the node attribute dictionaries for the nodes present in the needed frame.
For example for PhC-C2DL-PSC, this leads to a ~3x speedup for matching.
> Speed up CTCMatcher

- .github/workflows/ci.yml
- pyproject.toml
`traccuracy` is failing to install on Mac/python 3.8 because `imagecodecs` has dropped support for python 3.8. I suggest that we follow suite and stop supporting python 3.8. If there is a better/easier solution, I'm happy to adopt it.
> Remove support for python 3.8

- src/traccuracy/matchers/_iou.py
- tests/matchers/test_iou.py
This PR adds an option to the `IOUMatcher` to force the mapping to be one-to-one using linear sum assignment. Enabling this option makes the `IOUMatcher` compatible with division metrics.
> Add iou matcher option to use linear assignment to get one-to-one matching

- src/traccuracy/_tracking_graph.py
- src/traccuracy/matchers/_ctc.py
- src/traccuracy/matchers/_iou.py
- src/traccuracy/track_errors/_ctc.py
- tests/test_tracking_graph.py
- tests/track_errors/test_ctc_errors.py
Fix bug related to empty induced subgraph when computing CTC errors. Also now throws an error in TrackingGraph.get_subgraph() when empty nodes are provided, which I'm not sure is the correct behavior, but an "empty" TrackingGraph is poorly defined (e.g. need start and end frame determined by data).
> Check empty subgraph

- .github/release.yml
Prettier release notes :) Not sure how to test it until we run a release
> Group PRs in release notes based on labels

- .github/ISSUE_TEMPLATE/features.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR gets rid of unnecessary check boxes in our PR and issue templates. Now we prompt to delete the items in the list that don't apply.
> Reduce number of checkboxes in issue and PR templates

- src/traccuracy/track_errors/divisions.py
- tests/metrics/test_divisions.py
- tests/test_utils.py
- tests/track_errors/test_divisions.py
@bentaculum I also saw issues with the frame buffer not updating when I expected it to. Upon closer inspection, there was a bug in how we were checking the successors. This PR fixes that bug. Sorry!
Previous discussion of possible frame buffer issue https://github.com/Janelia-Trackathon-2023/traccuracy/issues/100#issuecomment-1852330818
> Fix frame buffer bug where predecessors were not checked properly

- src/traccuracy/matchers/_ctc.py
- tests/examples/segs.py
- tests/matchers/test_ctc.py
Branch based on #173
- Use example segmentation tests cases for testing the ctc matcher
- Refactor the matcher to have a stand alone function that does the core matching of two frames (for easier testing)
- Matchers
> Test CTCMatcher using standard test cases

- tests/track_errors/test_divisions.py
> Test division errors using standard test cases

- src/traccuracy/_tracking_graph.py
- src/traccuracy/metrics/_ctc.py
- src/traccuracy/track_errors/_ctc.py
- tests/test_tracking_graph.py
- tests/track_errors/test_ctc_errors.py
Prefixes ctc specific flags with "CTC_". This will allow us to isolate the CTC specific annotations and in the future create our own set of edge and node annotations.
- Track Errors
> Rename CTC `NodeFlags` and `EdgeFlags`

- tests/track_errors/test_ctc_errors.py
Fixes #191 
When I tried, I couldn't reproduce the original issue that led us to comment out that block in the test. All I actually did here was update the code to reflect that GT nodes matched to a NS node are not annotated with any error type including FN.
- Track Errors
> Bugfix: fix testing issue with GT nodes matched to NS nodes

- src/traccuracy/metrics/_ctc.py
@DragaDoncila I was going to just add docstrings and type annotations, and then I noticed that the behavior was inconsistent between the different metrics for what happens when the denomintor is 0.
In this PR I change them all to warn and return np.nan, whereas previously the TRA raised a RuntimeError, the LNK warned and returned np.nan, and the DET did not check. I don't think I have strong opinions about which of these options is better, other than that checking for a zero denominator is good, so this is just a suggestion of one possible solution.
I didn't fix the tests, since I wanted your opinion on what the "correct" solution is first. Feel free to just pull the bits of code you want and treat this as a review rather than a PR - I just already wrote the code so I figured I would …
> Make consistent behavior when denom is 0 and add docstrings

- .github/workflows/ci.yml
- pyproject.toml
- scripts/test_case_report.py
This PR introduces a new github action workflow that measures coverage of each error and matcher module against our standard test cases in `tests.examples`. The action generates a plot which is linked in a comment on the commit similar to the benchmarking action that runs for PRs.
The script is written such that if new modules are added to track_errors or matchers they should be incorporated automatically. The same is true of functions in the `tests.examples`. However, I can't promise that the sizing of the plot will work out automatically.
Put an x in the boxes …
> Add workflow for generating a test case coverage report

- docs/source/matchers/matchers.md
- src/traccuracy/loaders/_ctc.py
- src/traccuracy/matchers/__init__.py
- src/traccuracy/matchers/_point_seg.py
- tests/bench.py
- tests/matchers/test_point_seg.py
This new matcher constructs a mapping between points and segmentations. Either the gt or the pred data can have segmentations, but only one can have segmentations.
> Implement a point to segmentation matcher

- src/traccuracy/cli.py
- tests/test_cli.py
Closes #79 to just use the CLI to run standard CTC metrics on CTC formatted data
Also adds in tests that actually runs the CLI with different arguments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did …
> Limit CLI to CTC only

- pyproject.toml
I think the latest `click` release (dependency of typer) broke `sphinx-click` because we get a [typer](https://app.readthedocs.org/projects/traccuracy/builds/28136770/#270632679--199) error when building CLI docs. Click was released last night. I've confirmed this locally on `main` as well - I actually don't know how to trigger a docs build without a commit, using the `pixi` workflow? But if I pin `click<8.2.0` it passes locally so I'm trying that here.
> Pin click dependency to avoid docs build failure

- src/traccuracy/_tracking_graph.py
- src/traccuracy/matchers/_point.py
- src/traccuracy/matchers/_point_seg.py
- tests/matchers/test_point.py
- tests/matchers/test_point_seg.py
- tests/test_tracking_graph.py
- tests/test_utils.py
Expands set of valid location keys to include a single location key holding a list of values, along with the existing tuple of keys holding one value each.
What types of changes does your code introduce?
Which topics does your change affect? 
We could rename the argument to "location_key", but that is a breaking change.
We could also pick one type of location key instead of supporting both formats, but that is another big …
> Allow positions stored as lists in a single attribute

- src/traccuracy/loaders/_point.py
- tests/loaders/test_point.py
This PR updates the points loader to ensure that the returned graph contains positive integer node IDs.
We did look at potentially regenerating the node IDs if they do not match the requirements, but it would be a huge headache to do this and still keep correspondence with the parent IDs so we decided to simply error.
- Loaders
> Ensure point loader always returns positive integer IDs

- src/traccuracy/track_errors/_basic.py
- src/traccuracy/track_errors/_ctc.py
- src/traccuracy/track_errors/_divisions.py
- tests/metrics/test_basic.py
- tests/test_utils.py
- tests/track_errors/test_basic.py
- tests/track_errors/test_ctc_errors.py
- tests/track_errors/test_divisions.py
This PR checks that error classification functions are being called with either both graphs having error annotations, or neither graph having error annotations. This ensures a user cannot end up with inconsistent annotations on graphs by accidentally re-running classification on a graph that already has errors annotated e.g. by keeping GT the same and only changing pred.
In future we may want to add a utility that "cleans" an annotated graph so that a user can reuse the graph without requiring a copy.
- Track Errors
Put an x in the boxes that apply. You can also fill these out after …
> Raise error if only one graph has error annotations
